controllerManager:
  manager:
    args:
    - --leader-elect
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsGroup: 65532
      runAsNonRoot: true
      runAsUser: 65532
    env:
      debug: "false"
      krakendChartPath: /var/config/krakendinstaller-1.0.0.tgz
      netpolEnabled: "true"
    image:
      repository: ghcr.io/hypefamily/krakend/krakend-operator
      tag: latest
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  replicas: 1
  serviceAccount:
    annotations: {}
kubernetesClusterDomain: cluster.local
metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  type: ClusterIP
webhookService:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  type: ClusterIP
