---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - krakend.nais.io
  resources:
  - apiendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - krakend.nais.io
  resources:
  - apiendpoints/finalizers
  verbs:
  - update
- apiGroups:
  - krakend.nais.io
  resources:
  - apiendpoints/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - krakend.nais.io
  resources:
  - krakends
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - krakend.nais.io
  resources:
  - krakends/finalizers
  verbs:
  - update
- apiGroups:
  - krakend.nais.io
  resources:
  - krakends/status
  verbs:
  - get
  - patch
  - update
