apiVersion: v2
name: krakend-operator-crds
description: A Helm chart for Krakend Operator CRDs
type: application
version: v0.3.3
sources:
  - https://github.com/hypefamily/krakend/tree/sync-upstream-main/charts/krakend-operator-crds
